/* FICHIER GENERE PAR MAKEFILE : NE PAS MODIFIER */
/* FILE GENERATED BY MAKEFILE : DO NOT MODIFY */
#define VLISPDIR  "/usr/local/lib/xbvlisp/"
#define DFILE     "/usr/local/lib/xbvlisp/aidvlisp.:dat"
#define SFILE     "/usr/local/lib/xbvlisp/aidvlisp.:sec"
#define INFILE    "/usr/local/lib/xbvlisp/aidvlisp.dat"
#define BVLISPSYS "/usr/local/lib/xbvlisp/bvlisp.sys"
