
/* %I%, %R%, %B%, %D%,  %T%,  %M% */
/*
 *			Patrick Greussay, Novembre 1982
 *	fons.h		pour les declarations de fonctions de vlisp
 *                      Ernesto Sendoya 1990-1991, Interface X-Systeme.
 */


#ifdef STDC_HEADERS
#define LISP_PROTO   void
#else
#define LISP_PROTO
#endif

extern Int getpackage(LISP_PROTO),
  lastwin(LISP_PROTO),
  undo(LISP_PROTO),
/*  restart(LISP_PROTO), */
  changeval(LISP_PROTO),
  ldim(LISP_PROTO),
  cursorpos(LISP_PROTO),
  lwindowp(LISP_PROTO),
  iswidget(LISP_PROTO), /* lwindowp doit disparaitre pour donner lieu a un traitement homogne des widgets */
  isobjet(LISP_PROTO),
  isressource(LISP_PROTO),
  _putchar(LISP_PROTO),
  bufstr(LISP_PROTO),
  unbou(LISP_PROTO),
  eol(LISP_PROTO),
  read3_1(LISP_PROTO),
  read3_2(LISP_PROTO),
  read43_A(LISP_PROTO),
  oval(LISP_PROTO),
  RPT(LISP_PROTO),
  smash(LISP_PROTO),
  nmemq(LISP_PROTO),
  vmemq(LISP_PROTO),
  cassq(LISP_PROTO),
  setcassq(LISP_PROTO),
  chartyp(LISP_PROTO),
  Abs(LISP_PROTO),
  rtext(LISP_PROTO),
  stol(LISP_PROTO),
  ltos(LISP_PROTO),
  power(LISP_PROTO),
  stdmenu(LISP_PROTO),
  monit(LISP_PROTO),
  pour(LISP_PROTO),
  copyall(LISP_PROTO),
  waitp(LISP_PROTO),
  include(LISP_PROTO),
  background(LISP_PROTO),
  ibase(LISP_PROTO),
  stringi(LISP_PROTO),
  print_strings(LISP_PROTO),
  obase(LISP_PROTO),
  date(LISP_PROTO),
  timepp(LISP_PROTO),
  titre(LISP_PROTO),
  scroll(LISP_PROTO),
  isuser(LISP_PROTO),
  typech(LISP_PROTO),
  nodmc(LISP_PROTO),
  undmc(LISP_PROTO),
  redmc(LISP_PROTO),
  step(LISP_PROTO),
  unstep(LISP_PROTO),
  package(LISP_PROTO),
  aide(LISP_PROTO),
  section(LISP_PROTO),
  listesection(LISP_PROTO),
  output(LISP_PROTO),
  /* window(LISP_PROTO),  ligne(LISP_PROTO), */
  dml(LISP_PROTO),
  rdmac10(LISP_PROTO),
  readlin(LISP_PROTO),
  boundp(LISP_PROTO),
  clearcar(LISP_PROTO),
  clearcdr(LISP_PROTO),
  macout(LISP_PROTO),
  nomacout(LISP_PROTO),
  makemenu(LISP_PROTO),
  menu(LISP_PROTO),
  pro32(LISP_PROTO),
  probc33(LISP_PROTO),
  pannot(LISP_PROTO),
  pann1(LISP_PROTO),
  prob3_1A(LISP_PROTO),
  prob4A(LISP_PROTO),
  getcar(LISP_PROTO),
  getcdr(LISP_PROTO),
  putcar(LISP_PROTO),
  putcdr(LISP_PROTO),
  add1(LISP_PROTO),
  addprop(LISP_PROTO),
  and(LISP_PROTO),
  and_1(LISP_PROTO),
  and_2(LISP_PROTO),
  apexp(LISP_PROTO),
  append(LISP_PROTO),
  append(LISP_PROTO),
  /*  apply(LISP_PROTO), */
  apply2(LISP_PROTO),
  apply3(LISP_PROTO),
  apply_1(LISP_PROTO),
  argcp(LISP_PROTO),
  argvp(LISP_PROTO),
  assoc(LISP_PROTO),
  assoc_1(LISP_PROTO),
  assq(LISP_PROTO),
  assq_1(LISP_PROTO),
  atoip(LISP_PROTO),
  atom(LISP_PROTO),
  atomp(LISP_PROTO),
  attach(LISP_PROTO),
  careful(LISP_PROTO),
  ival(LISP_PROTO),
  clrival(LISP_PROTO),
  caaar(LISP_PROTO),
  caadr(LISP_PROTO),
  caar(LISP_PROTO),
  cadar(LISP_PROTO),
  caddr(LISP_PROTO),
  cadr(LISP_PROTO),
  carp(LISP_PROTO),
  cdaar(LISP_PROTO),
  cdadr(LISP_PROTO),
  cdar(LISP_PROTO),
  cddar(LISP_PROTO),
  cdddr(LISP_PROTO),
  cddr(LISP_PROTO),
  cdrp(LISP_PROTO),
  closure(LISP_PROTO),
  cond(LISP_PROTO),
  cond_1(LISP_PROTO),
  cond_2(LISP_PROTO),
  config(LISP_PROTO),
  consp(LISP_PROTO),
  copy(LISP_PROTO),
  copy_1(LISP_PROTO),
  copy_2(LISP_PROTO),
  crato(LISP_PROTO),
  /* ctrlz(LISP_PROTO),*/
  de(LISP_PROTO),
  Break(LISP_PROTO),
  debut(LISP_PROTO),
  debut_1(LISP_PROTO),
  debut_2(LISP_PROTO),
  decr(LISP_PROTO),
  decr_1(LISP_PROTO),
  def(LISP_PROTO),
  delet_1(LISP_PROTO),
  delet_2(LISP_PROTO),
  delete(LISP_PROTO),
  delq(LISP_PROTO),
  delq_1(LISP_PROTO),
  delq_2(LISP_PROTO),
  deset(LISP_PROTO),
  deset_1(LISP_PROTO),
  df(LISP_PROTO),
  differ(LISP_PROTO),
  disable(LISP_PROTO),
  dm(LISP_PROTO),
  dmc(LISP_PROTO),
  dmo(LISP_PROTO),
  dupl(LISP_PROTO),
  enable(LISP_PROTO),
  enabl_1(LISP_PROTO),
  eof(LISP_PROTO),
  eq(LISP_PROTO),
  equa2(LISP_PROTO),
  equa2_1(LISP_PROTO),
  equal(LISP_PROTO),
  erexit(LISP_PROTO),
  erindf_1(LISP_PROTO),
  erindfun(LISP_PROTO),
  erindvar(LISP_PROTO),
  ertyparg(LISP_PROTO),
  check_error(LISP_PROTO),
  check_arg(LISP_PROTO),
  erlec(LISP_PROTO),
  erpil(LISP_PROTO),
  erpil(LISP_PROTO),
  error(LISP_PROTO),
  error_0(LISP_PROTO),
  error_1(LISP_PROTO),
  erself(LISP_PROTO),
  erstr(LISP_PROTO),
  escape(LISP_PROTO),
  /*  eval(LISP_PROTO), */
  eval2(LISP_PROTO),
  eval2_1(LISP_PROTO),
  eval2_2(LISP_PROTO),
  eval3(LISP_PROTO),
  eval3_1(LISP_PROTO),
  eval3_2(LISP_PROTO),
  eval3_3(LISP_PROTO),
  /*  evalfu(LISP_PROTO), */
  evaln_1(LISP_PROTO),
  evaln_2(LISP_PROTO),
  evals_1(LISP_PROTO),
  /*  evca1(LISP_PROTO),*/
  evcls(LISP_PROTO),
  evesc(LISP_PROTO),
  evesc_1(LISP_PROTO),
  evexp(LISP_PROTO),
  evexp_0(LISP_PROTO),
  evexp_1(LISP_PROTO),
  evexp_2(LISP_PROTO),
  evexp_3(LISP_PROTO),
  evexp_4(LISP_PROTO),
  evexp_5(LISP_PROTO),
  evexp_6(LISP_PROTO),
  evexpn(LISP_PROTO),
  evfexb(LISP_PROTO),
  evfexp(LISP_PROTO),
  evlis(LISP_PROTO),
  evlis_1(LISP_PROTO),
  evlis_2(LISP_PROTO),
  evmac(LISP_PROTO),
  exitp(LISP_PROTO),
  explo_1(LISP_PROTO),
  explode(LISP_PROTO),
  fo_1(LISP_PROTO),
  foo(LISP_PROTO),
  forkp(LISP_PROTO),
  frame(LISP_PROTO),
  fread1(LISP_PROTO),
  freadp(LISP_PROTO),
  ftyp(LISP_PROTO),
  fval(LISP_PROTO),
  gc(LISP_PROTO),
  ge(LISP_PROTO),
  gensy_1(LISP_PROTO),
  gensym(LISP_PROTO),
  get(LISP_PROTO),
  getch1(LISP_PROTO),
  getch_1(LISP_PROTO),
  getcv(LISP_PROTO),
  getcv_1(LISP_PROTO),
  getcv_2(LISP_PROTO),
  getenp(LISP_PROTO),
  gt(LISP_PROTO),
  home(LISP_PROTO),
  ifnp(LISP_PROTO),
  ifnp_1(LISP_PROTO),
  ifp(LISP_PROTO),
  ifp_1(LISP_PROTO),
  implo_1(LISP_PROTO),
  implode(LISP_PROTO),
  incdec(LISP_PROTO),
  inchb(LISP_PROTO),
  incr(LISP_PROTO),
  incr_1(LISP_PROTO),
  internal(LISP_PROTO),
  intern_1(LISP_PROTO),
  itoap(LISP_PROTO),
  lambdap(LISP_PROTO),
  last(LISP_PROTO),
  lclose(LISP_PROTO),
  le(LISP_PROTO),
  length(LISP_PROTO),
  letdic(LISP_PROTO),
  letdicq(LISP_PROTO),
  letdi_1(LISP_PROTO),
  letdi_2(LISP_PROTO),
  llet(LISP_PROTO),
  letf(LISP_PROTO),
  lib(LISP_PROTO),
  lib_2(LISP_PROTO),
  libi(LISP_PROTO),
  linput(LISP_PROTO),
  listp(LISP_PROTO),
  litatom(LISP_PROTO),
  lockp(LISP_PROTO),
  logand(LISP_PROTO),
  lognot(LISP_PROTO),
  logor(LISP_PROTO),
  logshift(LISP_PROTO),
  logxor(LISP_PROTO),
  lopen(LISP_PROTO),
  lt(LISP_PROTO),
  macexp(LISP_PROTO),
  mcons(LISP_PROTO),
  member(LISP_PROTO),
  membr_1(LISP_PROTO),
  memq(LISP_PROTO),
  memq_1(LISP_PROTO),
  mul(LISP_PROTO),
  nconc(LISP_PROTO),
  neq(LISP_PROTO),
  newl(LISP_PROTO),
  newl_1(LISP_PROTO),
  nextl(LISP_PROTO),
  nreverse(LISP_PROTO),
  nth(LISP_PROTO),
  nullp(LISP_PROTO),
  numbp(LISP_PROTO),
  oblist(LISP_PROTO),
  myoblist(LISP_PROTO), /* oblist avec du hash */
  check_hash(LISP_PROTO),
  or(LISP_PROTO),
  or_1(LISP_PROTO),
  outpos(LISP_PROTO),
  pairlis(LISP_PROTO),
  peekc_1(LISP_PROTO),
  peekch(LISP_PROTO),
  plength(LISP_PROTO),
  plus(LISP_PROTO),
  popa1(LISP_PROTO),
  popj(LISP_PROTO),
  poscur(LISP_PROTO),
  prato(LISP_PROTO),
  prato_2(LISP_PROTO),
  prch(LISP_PROTO),
  prch_1(LISP_PROTO),
  prich_1(LISP_PROTO),
  prin1(LISP_PROTO),
  princ(LISP_PROTO),
  princh(LISP_PROTO),
  prini(LISP_PROTO),
  print(LISP_PROTO),
  allprint(LISP_PROTO),
  allprin1(LISP_PROTO),
  extprint(LISP_PROTO),
  extprin1(LISP_PROTO),
  allread(LISP_PROTO),
  allrend(LISP_PROTO),
  print(LISP_PROTO),
  prnum(LISP_PROTO),
  prob1(LISP_PROTO),
  prob3(LISP_PROTO),
  prob3_1(LISP_PROTO),
  prob4(LISP_PROTO),
  probc(LISP_PROTO),
  probef(LISP_PROTO),
  probj(LISP_PROTO),
  prog1(LISP_PROTO),
  prog1_1(LISP_PROTO),
  progn(LISP_PROTO),
  prspc(LISP_PROTO),
  prstr(LISP_PROTO),
  prstr_1(LISP_PROTO),
  put(LISP_PROTO),
  pvcch(LISP_PROTO),
  pvch(LISP_PROTO),
  quasiquote(LISP_PROTO),
  quo(LISP_PROTO),
  randomp(LISP_PROTO),
  rd1(LISP_PROTO),
  rd1_1(LISP_PROTO),
  rd2(LISP_PROTO),
  rd4(LISP_PROTO),
  rd4_1(LISP_PROTO),
  rd4_2(LISP_PROTO),
  rdmabq(LISP_PROTO),
  rdmabq_1(LISP_PROTO),
  rdmac(LISP_PROTO),
  rdmaq(LISP_PROTO),
  rdmaq_1(LISP_PROTO),
  rdmau(LISP_PROTO),
  rdmau_1(LISP_PROTO),
  rdmau_2(LISP_PROTO),
  rdst(LISP_PROTO),
  rdst_1(LISP_PROTO),
  rdst_2(LISP_PROTO),
  rdst_3(LISP_PROTO),
  read0(LISP_PROTO),
  read1_1(LISP_PROTO),
  read2_1(LISP_PROTO),
  read2_2(LISP_PROTO),
  read213(LISP_PROTO),
  read214(LISP_PROTO),
  read215(LISP_PROTO),
  read3(LISP_PROTO),
  read4(LISP_PROTO),
  read43(LISP_PROTO),
  read52(LISP_PROTO),
  readc_1(LISP_PROTO),
  readch(LISP_PROTO),
  readcr(LISP_PROTO),
  readi(LISP_PROTO),
  readline(LISP_PROTO),
  readu(LISP_PROTO),
  readu_1(LISP_PROTO),
  red48_1(LISP_PROTO),
  red48_2(LISP_PROTO),
  reent(LISP_PROTO),
  rem(LISP_PROTO),
  remob(LISP_PROTO),
  remprop(LISP_PROTO),
  repea_1(LISP_PROTO),
  repea_2(LISP_PROTO),
  repeat(LISP_PROTO),
  reverse(LISP_PROTO),
  rplac(LISP_PROTO),
  rplaca(LISP_PROTO),
  rplacb(LISP_PROTO),
  rplacd(LISP_PROTO),
  selectq(LISP_PROTO),
  self(LISP_PROTO),
  seltq_1(LISP_PROTO),
  seltq_2(LISP_PROTO),
  seltq_3(LISP_PROTO),
  seltq_4(LISP_PROTO),
  sessp(LISP_PROTO),
  set(LISP_PROTO),
  setq(LISP_PROTO),
  setq(LISP_PROTO),
  setq_1(LISP_PROTO),
  change_repertoire(LISP_PROTO),
  ls(LISP_PROTO),
  ssh(LISP_PROTO),
  sh(LISP_PROTO),
  status(LISP_PROTO),
  stop(LISP_PROTO),
  strcar(LISP_PROTO),
  strlenp(LISP_PROTO),
  strcatp(LISP_PROTO),
  strcdrp(LISP_PROTO),
  strcmpp(LISP_PROTO),
  stringp(LISP_PROTO),
  sub1(LISP_PROTO),
  subli_1(LISP_PROTO),
  subli_2(LISP_PROTO),
  sublis(LISP_PROTO),
  subst(LISP_PROTO),
  subst_1(LISP_PROTO),
  subst_2(LISP_PROTO),
  tags(LISP_PROTO),
  terpr0(LISP_PROTO),
  terpri(LISP_PROTO),
  timep(LISP_PROTO),
  toplv(LISP_PROTO),
  toplv_1(LISP_PROTO),
  toplv_2(LISP_PROTO),
  tryat(LISP_PROTO),
  ttyp(LISP_PROTO),
  tyi(LISP_PROTO),
  tyo(LISP_PROTO),
  tyoesc(LISP_PROTO),
  typch(LISP_PROTO),
  udfa(LISP_PROTO),
  udfe(LISP_PROTO),
  unbind(LISP_PROTO),
  unlessp(LISP_PROTO),
  until(LISP_PROTO),
  until_1(LISP_PROTO),
  until_2(LISP_PROTO),
  unwind(LISP_PROTO),
  done(LISP_PROTO),
  unwinp(LISP_PROTO),
  userp(LISP_PROTO),
  when_1(LISP_PROTO),
  whenp(LISP_PROTO),
  wheresc(LISP_PROTO),
  while_1(LISP_PROTO),
  while_2(LISP_PROTO),
  whilep(LISP_PROTO),
  zerop(LISP_PROTO);

#ifndef NO_VFLO
Int cosp(LISP_PROTO),
  pfix(LISP_PROTO),
  pfixp(LISP_PROTO),
  pfloat(LISP_PROTO),
  pfloatp(LISP_PROTO),
  prflo(LISP_PROTO),
  sinp(LISP_PROTO),
  asinp(LISP_PROTO),
  acosp(LISP_PROTO),
  atanp(LISP_PROTO),
  atan2p(LISP_PROTO),
  sqrtp(LISP_PROTO),
  expp(LISP_PROTO),logp(LISP_PROTO); /* deffinis en init.c comme ramenant des doubles ? */

#endif

#ifdef SFI_TRACE
Int sfi_trace(LISP_PROTO),
    sfi_mark(LISP_PROTO);
#endif

/* memory ... */
extern Int atomuses(LISP_PROTO),
  struses(LISP_PROTO),
  listuses(LISP_PROTO),
  flouses(LISP_PROTO),
  numuses(LISP_PROTO),
  piluses(LISP_PROTO);

/* X_SYSTEM */
Int  lcrewin(LISP_PROTO), 
  lchangewin(LISP_PROTO),
  lcresubwin(LISP_PROTO), 
  xwininfos(LISP_PROTO),   
  UnMapWid(LISP_PROTO),   
  MapWid(LISP_PROTO),  
  xRemoveWidget(LISP_PROTO),     
  xkillInterf(LISP_PROTO), 
  xwst(LISP_PROTO),    
  lwin(LISP_PROTO),    
  grab(LISP_PROTO),    
  xPopup(LISP_PROTO),
  xPopdown(LISP_PROTO),
  xBeep(LISP_PROTO),
  ungrab(LISP_PROTO),  
  xflush(LISP_PROTO),  
  xsleep(LISP_PROTO),  
  xconfirm(LISP_PROTO),
  xdialog(LISP_PROTO),
  gauche(LISP_PROTO),
  shift_gauche(LISP_PROTO),
  cleol(LISP_PROTO), 
  cleos(LISP_PROTO), 
  droite(LISP_PROTO),
  shift_droite(LISP_PROTO),
  bas(LISP_PROTO),
  haut(LISP_PROTO),
  back(LISP_PROTO),
  xscroll(LISP_PROTO),
  xEnable(LISP_PROTO), xDisable(LISP_PROTO),
  
  /* NEW Fonctios */
  /****************/
  
  xcretop(LISP_PROTO),
  xcrelispwin(LISP_PROTO),
  xcredrawin(LISP_PROTO),
  xRealize(LISP_PROTO) ,
  xUnrealize(LISP_PROTO),
  xManage(LISP_PROTO), 
  xUnmanage(LISP_PROTO),

  xSetValues(LISP_PROTO) ,
  xGetValues(LISP_PROTO) ,
  xGetWindow(LISP_PROTO),

  xGetResRepType(LISP_PROTO),
  xGetResourceList(LISP_PROTO),
  xGetNewResourceList(LISP_PROTO),
  xGetAllResourceLists(LISP_PROTO),

  xcalculdim(LISP_PROTO),
  xCircSubWidgets(LISP_PROTO),

  /* fonctions pour dessiner */
  
  xdrawarc(LISP_PROTO),
  xfillarc(LISP_PROTO),
  xdrawrectangle(LISP_PROTO),
  xfillrectangle(LISP_PROTO),
  xdrawstring(LISP_PROTO),
  xgetstringdim(LISP_PROTO),
  xcleararea(LISP_PROTO),
  xFillPolygon(LISP_PROTO),
  xDrawLine(LISP_PROTO),
  xDrawRay(LISP_PROTO),
  xDrawPoints(LISP_PROTO),
  xsetForeground(LISP_PROTO),
  xsetBackground(LISP_PROTO),
  xDisplayBitmap(LISP_PROTO),
  xmodifyGC(LISP_PROTO),
  xgetGCvalue(LISP_PROTO),

  /* manipulation du pointeur de la souris */
  xgetpospointer(LISP_PROTO),
  pospointer(LISP_PROTO),
  /* le curseur */
  xGetCursorpos(LISP_PROTO),
  
  /* configuration d'objets
     graphiques de bas niveau */
  
  xsetState(LISP_PROTO),
  xsetTrace(LISP_PROTO),
  
  /* la tortue */
  xcretortue (LISP_PROTO) ,
  deplace_tortue(LISP_PROTO),
  pos_tortue(LISP_PROTO),
  getpos_tortue(LISP_PROTO),
  pencilOn(LISP_PROTO),
  pencilOff(LISP_PROTO),
  tortueOn(LISP_PROTO),
  tortueOff(LISP_PROTO),

  /* la VRAIE Tortue */
  AvanceTortue(LISP_PROTO),

  xwsave(LISP_PROTO),
  /* premiers objets graphiques */
  xCreateResource(LISP_PROTO),
  xsetRessource(LISP_PROTO),
  xcreeWidget(LISP_PROTO),
  xWidgetParent(LISP_PROTO),
  /* ajout des callbacks */
  xaddCallback(LISP_PROTO),
  /* des essai avec la src. de widgettes text */
  xchgsrc(LISP_PROTO),
  /* ajout des translations */
  xAugmentTranslation(LISP_PROTO),
  xOverrideTranslation(LISP_PROTO),
  /* des evenements */
  xCheckEvent(LISP_PROTO),
  xisrealized(LISP_PROTO)
;

/* Prolog */
Int assert(LISP_PROTO),
  cut(LISP_PROTO),
  fail(LISP_PROTO),
  iequate(LISP_PROTO),
  iequa_0(LISP_PROTO),
  var(LISP_PROTO),
  univ(LISP_PROTO),
  iequa_1(LISP_PROTO),
  lisp(LISP_PROTO),
  affpro(LISP_PROTO),
  preequate(LISP_PROTO),
  prolog(LISP_PROTO),
  unifail(LISP_PROTO),
  unifsuc(LISP_PROTO),
  unify(LISP_PROTO);

/* Open/Mesa GL */
#if (OPEN_GL | MESA_GL)
#if MODIFIEDMESA
Int mesaCopy(LISP_PROTO),
  mesaWriteList(LISP_PROTO),
  mesaReadList(LISP_PROTO),
  mesaGetList(LISP_PROTO);
#endif
Int glLibInit(LISP_PROTO),
  gl_dump_window(LISP_PROTO),
  gl_load_polygon_stipple(LISP_PROTO),
  gl_read_tiff(LISP_PROTO),
  gl_read_rgb(LISP_PROTO),
  gl_winopen(LISP_PROTO),
  gl_winclose(LISP_PROTO),
  gl_winset(LISP_PROTO),
  gl_addcallback(LISP_PROTO),
  gl_swapbuffer(LISP_PROTO),
  gl_swap_tmesh(LISP_PROTO),
  gl_flush(LISP_PROTO),
  gl_swap_interval(LISP_PROTO), 
  gl_couleur(LISP_PROTO),
  gl_Couleur(LISP_PROTO),
  gl_clear(LISP_PROTO),
  gl_rectcpy(LISP_PROTO),
  gl_rectzoom(LISP_PROTO),
  gl_bgn(LISP_PROTO),
  gl_fini(LISP_PROTO),
  gl_epaisseur(LISP_PROTO),
  gl_style(LISP_PROTO),
  gl_vertex(LISP_PROTO),
  gl_normal(LISP_PROTO),
  gl_bezier_mesh_2(LISP_PROTO),
  gl_bezier_grid_2(LISP_PROTO),
  gl_bezier_eval_2(LISP_PROTO),
  gl_bezier_map_2(LISP_PROTO),
  gl_bezier_mesh_1(LISP_PROTO),
  gl_bezier_grid_1(LISP_PROTO),
  gl_bezier_eval_1(LISP_PROTO),
  gl_bezier_map_1(LISP_PROTO),
  gl_set_nurbs(LISP_PROTO),
  gl_nurbs_curve(LISP_PROTO),
  gl_nurbs_surface(LISP_PROTO),
  gl_ortho(LISP_PROTO),
  gl_frustum(LISP_PROTO),
  gl_auto_perspective(LISP_PROTO),
  gl_window(LISP_PROTO),
  gl_perspective(LISP_PROTO),
  gl_lookat(LISP_PROTO),
  gl_polarv(LISP_PROTO),
  gl_mmode(LISP_PROTO),
  gl_loadnom(LISP_PROTO),
  gl_pushnom(LISP_PROTO),
  gl_popnom(LISP_PROTO),
  gl_pushmatrice(LISP_PROTO),
  gl_popmatrice(LISP_PROTO),
  gl_loadidmatrix(LISP_PROTO),
  gl_echelle(LISP_PROTO),
  gl_translat(LISP_PROTO),
  gl_rotate_order(LISP_PROTO),
  gl_rotate(LISP_PROTO),
  gl_rotate_axis(LISP_PROTO), 
  gl_translate_image(LISP_PROTO),
  gl_rotate_image(LISP_PROTO),
  gl_scale_image(LISP_PROTO),
  gl_circle(LISP_PROTO),
  gl_get_valeur(LISP_PROTO),
  gl_get_circle_pos(LISP_PROTO),
  gl_get_real_position(LISP_PROTO),
  gl_get_matrix(LISP_PROTO),
  gl_matrix_load(LISP_PROTO), 
  gl_matrix_mult(LISP_PROTO),
  gl_get_matrix_value(LISP_PROTO), 
  gl_set_matrix_value(LISP_PROTO), 
  get_image_transformation(LISP_PROTO),
  gl_free_matrix(LISP_PROTO), 
  gl_sphere(LISP_PROTO),
  gl_rect(LISP_PROTO),
  gl_rectf(LISP_PROTO),
  gl_polyg(LISP_PROTO),
  gl_polym(LISP_PROTO),
  /* fonctions Hershey */
  glhfont(LISP_PROTO),
  glhpath(LISP_PROTO),
  glhdrawchar(LISP_PROTO),
  glhstr(LISP_PROTO),
  glhtextsize(LISP_PROTO),
  glhboxtext(LISP_PROTO),
  glhboxfit(LISP_PROTO),
  glhtextangl(LISP_PROTO),
  glhfixedwidth(LISP_PROTO),
  glhcentertext(LISP_PROTO),
  glhrigthjustify(LISP_PROTO),
  glhleftjustify(LISP_PROTO),
  gl_string(LISP_PROTO),
  /* textures */
  gl_def_tiff_texture(LISP_PROTO),
  gl_def_rgb_texture(LISP_PROTO), 
  gl_def_data_texture(LISP_PROTO),
  gl_texture_coord(LISP_PROTO),
  gl_texture_env(LISP_PROTO),
  gl_texture_parameter(LISP_PROTO),
  gl_texture_gen(LISP_PROTO),
  gl_pousse_attrib(LISP_PROTO),
  gl_tire_attrib(LISP_PROTO),
  gl_copy_attrib(LISP_PROTO),
  gl_islist(LISP_PROTO),
  gl_setrootlist(LISP_PROTO),
  gl_genlist(LISP_PROTO),
  gl_newlist(LISP_PROTO),
  gl_endlist(LISP_PROTO),
  gl_dellist(LISP_PROTO),
  gl_calllist(LISP_PROTO),
  gl_pushnewlist(LISP_PROTO),
  gl_cylinder(LISP_PROTO),
  gl_disk(LISP_PROTO),
  gl_fonction_blend(LISP_PROTO),
  gl_lumiere(LISP_PROTO),
  gl_model(LISP_PROTO),
  gl_materiel(LISP_PROTO),
  gl_is_enable(LISP_PROTO),
  gl_permet(LISP_PROTO),
  gl_disable(LISP_PROTO),
  glu_delquad(LISP_PROTO),
  glu_setvalue(LISP_PROTO),
  gl_sphere_wire(LISP_PROTO),
  gl_cube_wire(LISP_PROTO),
  gl_box_wire(LISP_PROTO),
  gl_torus_wire(LISP_PROTO),
  gl_cylinder_wire(LISP_PROTO),
  gl_icosahedra_wire(LISP_PROTO),
  gl_octahedra_wire(LISP_PROTO),
  gl_tetrahedra_wire(LISP_PROTO),
  gl_dodecahedra_wire(LISP_PROTO),
  gl_cone_wire(LISP_PROTO),
  gl_sphere_solid(LISP_PROTO),
  gl_cube_solid(LISP_PROTO),
  gl_box_solid(LISP_PROTO),
  gl_torus_solid(LISP_PROTO),
  gl_cylinder_solid(LISP_PROTO),
  gl_icosahedra_solid(LISP_PROTO),
  gl_octahedra_solid(LISP_PROTO),
  gl_tetrahedra_solid(LISP_PROTO),
  gl_dodecahedra_solid(LISP_PROTO),
  gl_cone_solid(LISP_PROTO);
#endif

/* sockects */
Int soCreate(LISP_PROTO),
  soClose(LISP_PROTO),
  soListen(LISP_PROTO),
  soConnect(LISP_PROTO),
  soWrite(LISP_PROTO),
  soHostName(LISP_PROTO),
  soRead(LISP_PROTO) ;

