/* FICHIER GENERE PAR MAKEFILE : NE PAS MODIFIER */
/* FILE GENERATED BY MAKEFILE : DO NOT MODIFY */
#define VLISPDIR  "/usr/share/xbvlisp/"
#define DFILE     "/usr/share/xbvlisp/aidvlisp.:dat"
#define SFILE     "/usr/share/xbvlisp/aidvlisp.:sec"
#define INFILE    "/usr/share/xbvlisp/aidvlisp.dat"
#define BVLISPSYS "/usr/share/xbvlisp/bvlisp.sys"
