# Makefile.in generated automatically by automake 1.4-p6 from Makefile.am

# Copyright (C) 1994, 1995-8, 1999, 2001 Free Software Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.

# SUBDIRS = bitmap


SHELL = /bin/bash

srcdir = .
top_srcdir = ..

prefix = /usr/local
exec_prefix = ${prefix}

bindir = ${exec_prefix}/bin
sbindir = ${exec_prefix}/sbin
libexecdir = ${exec_prefix}/libexec
datadir = ${prefix}/share
sysconfdir = ${prefix}/etc
sharedstatedir = ${prefix}/com
localstatedir = ${prefix}/var
libdir = ${exec_prefix}/lib
infodir = ${prefix}/share/info
mandir = ${prefix}/share/man
includedir = ${prefix}/include
oldincludedir = /usr/include

DESTDIR =

pkgdatadir = $(datadir)/xbvl
pkglibdir = $(libdir)/xbvl
pkgincludedir = $(includedir)/xbvl

top_builddir = ..

ACLOCAL = /home/gunter/GM_LANGUAGES/Functional_Languages/LISP_Dialects/XBVLisp_GM/xbvl-2.2.3-light/missing aclocal-1.4
AUTOCONF = autoconf
AUTOMAKE = /home/gunter/GM_LANGUAGES/Functional_Languages/LISP_Dialects/XBVLisp_GM/xbvl-2.2.3-light/missing automake-1.4
AUTOHEADER = autoheader

INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL} $(AM_INSTALL_PROGRAM_FLAGS)
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_SCRIPT = ${INSTALL}
transform = s,x,x,

NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
host_alias = 
host_triplet = x86_64-unknown-linux-gnu
ARFLAGS = ruv
CC = gcc
#CFLAGS = -O3  -pipe -DSHM
CFLAGS = -m32 -g  -pipe -DSHM
CPP = gcc -E
DATA_TYPE = int
EMACS = /usr/bin/emacs
HAVE_DIRNAME = -DHAVE_INDEX
HAVE_ERRNO = -DERRNO
HAVE_INDEX = 
HAVE_LIB = @HAVE_LIB@
HAVE_PROTOENT = -DGETPROTENT
HAVE_XRBFD = 
LIB = @LIB@
LN_S = ln -s
LTLIB = @LTLIB@
MAKEINFO = makeinfo
MODIFIEDMESA = 
NO_VFLO = 
PACKAGE = xbvl
RANLIB = ranlib
SYS_CFLAGS =  -pipe -DSHM
SYS_LDFLAGS =  
TIFF_DEF = 
TIFF_LIB = 
VERSION = 2.2.3-light
XAW_DIR = 
XAW_LIB = 
X_USE_LATIN1 = -DX_USE_LATIN1
lispdir = $(prefix)/share/emacs/site-lisp

EXTRA_DIST = EDIT.vlisp GL-Drive-Help.txt GL-drive.vlisp GL-lib.vlisp LisptoTex 	LisptoTex.c NewComms.txt README 	Tree.vlisp X-Menus.vlisp adapt.sed adapte aide.c aidvl-gl.txt 	aidvl-so.txt aidvl1.txt aidvl2.txt aidvlr.txt all.vlisp azer.demo 	azer.vlisp boy.vlisp bvlisp.ini bvlisp.sys con.vlisp 	cons-p.vlisp conte.vlisp conv.vlisp cour.vlisp editAide.txt ef-pg.vlisp 	eff.vlisp essai.vlisp eval.vlisp eval1.vlisp getdoc.vlisp gg.vlisp 	i-val.vlisp io.vlisp lib.vlisp libpro.vlisp lisp_names.h match.ccl 	match.vlisp min.vlisp minser.vlisp mon.vlisp mon.vlisp.ok paraf.vlisp 	permut.vlisp phenar.vlisp pretty.vlisp profib.vlisp prt-pg.vlisp 	prt.vlisp prtt.vlisp rain.vlisp rec.vlisp record.vlisp rev.vlisp 	simpl.vlisp stepper.vlisp stp.vlisp test.demo test.vlisp tfunc.vlisp 	tortue.vlisp traaide.c traaide.script trac1.vlisp trace-pg.vlisp 	trace.vlisp vcg.cro vcg.vlisp vlisp.ini widget.vlisp xfile.vlisp 	xbvl.el


bin_PROGRAMS = traaide aide

lisp_LISP = xbvl.el

LISPLIBDIR = /usr/local/share/xbvlisp
mkinstalldirs = $(SHELL) $(top_srcdir)/mkinstalldirs
CONFIG_CLEAN_FILES = 
PROGRAMS =  $(bin_PROGRAMS)


DEFS = -DPACKAGE_NAME=\"\" -DPACKAGE_TARNAME=\"\" -DPACKAGE_VERSION=\"\" -DPACKAGE_STRING=\"\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"xbvl\" -DVERSION=\"2.2.3-light\" -DSTDC_HEADERS=1 -I. -I$(srcdir) 
CPPFLAGS = 
LDFLAGS = 
LIBS = 
X_CFLAGS = 
X_LIBS = 
X_EXTRA_LIBS = 
X_PRE_LIBS =  -lSM -lICE
traaide_SOURCES = traaide.c
traaide_OBJECTS =  traaide.o
traaide_LDADD = $(LDADD)
traaide_DEPENDENCIES = 
traaide_LDFLAGS = 
aide_SOURCES = aide.c
aide_OBJECTS =  aide.o
aide_LDADD = $(LDADD)
aide_DEPENDENCIES = 
aide_LDFLAGS = 
COMPILE = $(CC) $(DEFS) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(LDFLAGS) -o $@
LISP =  $(lisp_LISP)

ELCFILES =  xbvl.elc
DIST_COMMON =  README Makefile.am Makefile.in elisp-comp


DISTFILES = $(DIST_COMMON) $(SOURCES) $(HEADERS) $(TEXINFOS) $(EXTRA_DIST)

TAR = tar
GZIP_ENV = --best
SOURCES = traaide.c aide.c
OBJECTS = traaide.o aide.o

all: all-redirect
.SUFFIXES:
.SUFFIXES: .S .c .el .elc .o .s
$(srcdir)/Makefile.in: Makefile.am $(top_srcdir)/configure.in $(ACLOCAL_M4) 
	cd $(top_srcdir) && $(AUTOMAKE) --gnu --include-deps src_data/Makefile

Makefile: $(srcdir)/Makefile.in  $(top_builddir)/config.status
	cd $(top_builddir) \
	  && CONFIG_FILES=$(subdir)/$@ CONFIG_HEADERS= $(SHELL) ./config.status


mostlyclean-binPROGRAMS:

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

distclean-binPROGRAMS:

maintainer-clean-binPROGRAMS:

install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	$(mkinstalldirs) $(DESTDIR)$(bindir)
	@list='$(bin_PROGRAMS)'; for p in $$list; do \
	  if test -f $$p; then \
	    echo "  $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`"; \
	     $(INSTALL_PROGRAM) $$p $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	  else :; fi; \
	done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	list='$(bin_PROGRAMS)'; for p in $$list; do \
	  rm -f $(DESTDIR)$(bindir)/`echo $$p|sed 's/$(EXEEXT)$$//'|sed '$(transform)'|sed 's/$$/$(EXEEXT)/'`; \
	done

.c.o:
	$(COMPILE) -c $<

.s.o:
	$(COMPILE) -c $<

.S.o:
	$(COMPILE) -c $<

mostlyclean-compile:
	-rm -f *.o core *.core

clean-compile:

distclean-compile:
	-rm -f *.tab.c

maintainer-clean-compile:

install-lispLISP: $(lisp_LISP) $(ELCFILES)
	@$(NORMAL_INSTALL)
	@if test -n "$(lispdir)"; then \
	  $(mkinstalldirs) $(DESTDIR)$(lispdir); \
	  list='$(lisp_LISP)'; for p in $$list; do \
	    if test -f "$$p"; then d= ; else d="$(srcdir)/"; fi; \
	    echo " $(INSTALL_DATA) $$d$$p $(DESTDIR)$(lispdir)/$$p"; \
	    $(INSTALL_DATA) $$d$$p $(DESTDIR)$(lispdir)/$$p; \
	    if test -f $${p}c; then \
	      echo " $(INSTALL_DATA) $${p}c $(DESTDIR)$(lispdir)/$${p}c"; \
	      $(INSTALL_DATA) $${p}c $(DESTDIR)$(lispdir)/$${p}c; \
	    else : ; fi; \
	  done; \
	else : ; fi

uninstall-lispLISP:
	@$(NORMAL_UNINSTALL)
	@if test -n "$(lispdir)"; then \
	  list='$(lisp_LISP)'; for p in $$list; do \
	    rm -f $(DESTDIR)$(lispdir)/$$p $(DESTDIR)$(lispdir)/$${p}c; \
	  done; \
	else : ; fi
.el.elc:
	@echo 'WARNING: Warnings can be ignored. :-)'
	if test $(EMACS) != no; then \
	  EMACS=$(EMACS) $(SHELL) $(srcdir)/elisp-comp $<; \
	fi

mostlyclean-lisp:

clean-lisp:
	-test -z "$(ELCFILES)" || rm -f $(ELCFILES)

distclean-lisp:

maintainer-clean-lisp:

tags: TAGS

ID: $(HEADERS) $(SOURCES) $(LISP)
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	here=`pwd` && cd $(srcdir) \
	  && mkid -f$$here/ID $$unique $(LISP)

TAGS:  $(HEADERS) $(SOURCES)  $(TAGS_DEPENDENCIES) $(LISP)
	tags=; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS)'; \
	unique=`for i in $$list; do echo $$i; done | \
	  awk '    { files[$$0] = 1; } \
	       END { for (i in files) print i; }'`; \
	test -z "$(ETAGS_ARGS)$$unique$(LISP)$$tags" \
	  || (cd $(srcdir) && etags -o $$here/TAGS $(ETAGS_ARGS) $$tags  $$unique $(LISP))

mostlyclean-tags:

clean-tags:

distclean-tags:
	-rm -f TAGS ID

maintainer-clean-tags:

distdir = $(top_builddir)/$(PACKAGE)-$(VERSION)/$(subdir)

subdir = src_data

distdir: $(DISTFILES)
	@for file in $(DISTFILES); do \
	  d=$(srcdir); \
	  if test -d $$d/$$file; then \
	    cp -pr $$d/$$file $(distdir)/$$file; \
	  else \
	    test -f $(distdir)/$$file \
	    || ln $$d/$$file $(distdir)/$$file 2> /dev/null \
	    || cp -p $$d/$$file $(distdir)/$$file || :; \
	  fi; \
	done

info-am:
info: info-am
dvi-am:
dvi: dvi-am
check-am: all-am
check: check-am
installcheck-am:
installcheck: installcheck-am
install-exec-am: install-binPROGRAMS
install-exec: install-exec-am

install-data-am: install-lispLISP
install-data: install-data-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am
install: install-am
uninstall-am: uninstall-binPROGRAMS uninstall-lispLISP
uninstall: uninstall-am
all-am: Makefile $(PROGRAMS) $(LISP) $(ELCFILES)
all-redirect: all-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) AM_INSTALL_PROGRAM_FLAGS=-s install
installdirs:
	$(mkinstalldirs)  $(DESTDIR)$(bindir) $(DESTDIR)$(lispdir)


mostlyclean-generic:

clean-generic:

distclean-generic:
	-rm -f Makefile $(CONFIG_CLEAN_FILES)
	-rm -f config.cache config.log stamp-h stamp-h[0-9]*

maintainer-clean-generic:
mostlyclean-am:  mostlyclean-binPROGRAMS mostlyclean-compile \
		mostlyclean-lisp mostlyclean-tags mostlyclean-generic

mostlyclean: mostlyclean-am

clean-am:  clean-binPROGRAMS clean-compile clean-lisp clean-tags \
		clean-generic mostlyclean-am

clean: clean-am

distclean-am:  distclean-binPROGRAMS distclean-compile distclean-lisp \
		distclean-tags distclean-generic clean-am

distclean: distclean-am

maintainer-clean-am:  maintainer-clean-binPROGRAMS \
		maintainer-clean-compile maintainer-clean-lisp \
		maintainer-clean-tags maintainer-clean-generic \
		distclean-am
	@echo "This command is intended for maintainers to use;"
	@echo "it deletes files that may require special tools to rebuild."

maintainer-clean: maintainer-clean-am

.PHONY: mostlyclean-binPROGRAMS distclean-binPROGRAMS clean-binPROGRAMS \
maintainer-clean-binPROGRAMS uninstall-binPROGRAMS install-binPROGRAMS \
mostlyclean-compile distclean-compile clean-compile \
maintainer-clean-compile uninstall-lispLISP install-lispLISP \
mostlyclean-lisp distclean-lisp clean-lisp maintainer-clean-lisp tags \
mostlyclean-tags distclean-tags clean-tags maintainer-clean-tags \
distdir info-am info dvi-am dvi check check-am installcheck-am \
installcheck install-exec-am install-exec install-data-am install-data \
install-am install uninstall-am uninstall all-redirect all-am all \
installdirs mostlyclean-generic distclean-generic clean-generic \
maintainer-clean-generic clean mostlyclean distclean maintainer-clean

aide: traaide
	$(CC) $(CFLAGS) -o aide aide.c
	cat aidvl?.txt > aidvlisp.dat
	if test -n "${AIDE_OPENGL}" ; then \
	    cat aidvl-gl.txt >> aidvlisp.dat ; \
	    cp  GL-Drive-Help.txt GL-Drive-Help.dat ; \
	    ./traaide f GL-Drive-Help ; \
	fi
	cat aidvl-so.txt >> aidvlisp.dat
	./traaide f aidvlisp

traaide: traaide.c lisp_names.h
	$(CC) $(CFLAGS) -o traaide traaide.c

install-data-am:
	$(mkinstalldirs) $(LISPLIBDIR)
#	$(INSTALL_DATA) bitmap/* $(BITMAPLIB)
	$(INSTALL_DATA) *.vlisp  $(LISPLIBDIR)
	$(INSTALL_DATA) *dat     $(LISPLIBDIR)
	$(INSTALL_DATA) *sec     $(LISPLIBDIR)
	$(INSTALL_DATA) *sys     $(LISPLIBDIR)

doc:  traaide
	./traaide l L f aidvlisp
	latex aidvlisp
	latex aidvlisp
	makeindex aidvlisp.idx
	latex aidvlisp
	dvips -o aidvlisp.ps aidvlisp.dvi

lisp_names.h: ../src_lisp/init.c
	grep "mkat(\"" ../src_lisp/init.c | sed -e s/.*mkat\(// | sed -e s/\".*\",.*/\"\1\",/ | sed -e s/\^\",/\",\",/ > src_atoms_tmp
	sed -e s/\"pour\",/\"*pour*\",/ < src_atoms_tmp | sort > src_atoms
	echo \#define NUM_LISP_NAMES `wc -l < src_atoms` > lisp_names.h
	echo static char *lisp_names\[NUM_LISP_NAMES+1\] = \{ >> lisp_names.h
	cat src_atoms >> lisp_names.h
	echo "NULL };" >> lisp_names.h
	rm -f src_atoms*

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
